name: sustainpdf
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pandas
  - numpy
  - matplotlib
  - scikit-learn
  - jupyterlab
  - pdfplumber
  - typer
  - rich
  - pydantic
  - pip:
      - pymupdf
      - -e .
